trigger: none

parameters:
  - name: environment
    displayName: 'Select environment'
    type: string
    default: 'frontend_production'
    values:
      - frontend_production
      - backend_production

jobs:
- job: frontend_production
  displayName: 'Build Frontend for Production'
  condition: eq('${{ parameters.environment }}', 'frontend_production')
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UseNode@1
    inputs:
      version: '20.9.0'
  - task: DownloadSecureFile@1
    name: sshKey
    inputs:
      secureFile: 'azure_pipelines_backoffice_admintool'
    displayName: 'Download SSH Private Key'
  - script: |
      mkdir -p ~/.ssh
      cp $(sshKey.secureFilePath) ~/.ssh/id_rsa
      chmod 600 ~/.ssh/id_rsa
      echo "StrictHostKeyChecking no" >> ~/.ssh/config
    displayName: 'Configure SSH Key'
  - script: |
      echo "Checking SSH connection"
      ssh -vvv -t web@65.21.20.215 "pwd && ls -al"
    displayName: 'Verify SSH Connection'
  - script: |
      echo "Installing dependencies for Frontend"
      cd frontend/frontend_admintool
      yarn install
    displayName: 'Install dependencies'
  - script: |
      echo "Building Frontend"
      cd frontend/frontend_admintool
      yarn build
    displayName: 'Build Frontend'
  - script: |
      echo "Deploying Frontend to server using rsync"
      BUILD_ID=$(date +%Y%m%d%H%M%S)
      ssh web@65.21.20.215 "mkdir -p /home/web/backoffice.admintool/releases/frontend_$BUILD_ID"
      rsync -avz frontend/frontend_admintool/dist/ web@65.21.20.215:/home/web/backoffice.admintool/releases/frontend_$BUILD_ID
      ssh web@65.21.20.215 "ln -sfn /home/web/backoffice.admintool/releases/frontend_$BUILD_ID /home/web/backoffice.admintool/releases/frontend_production_temp"
    displayName: 'Deploy Frontend'
  - script: |
      echo "Switching symlink to the new release"
      ssh web@65.21.20.215 "
        ln -sfn /home/web/backoffice.admintool/releases/frontend_production_temp /home/web/backoffice.admintool/releases/frontend_production &&
        rm -rf /home/web/backoffice.admintool/releases/frontend_production_temp
      "
    displayName: 'Switch Frontend Symlink'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'frontend/frontend_admintool/dist'
      ArtifactName: 'frontend_dist'
      publishLocation: 'Container'
    displayName: 'Publish Frontend Artifacts'

- job: backend_production
  displayName: 'Build Backend for Production'
  condition: eq('${{ parameters.environment }}', 'backend_production')
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UseNode@1
    inputs:
      version: '20.9.0'
  - task: DownloadSecureFile@1
    name: sshKey
    inputs:
      secureFile: 'azure_pipelines_backoffice_admintool'
    displayName: 'Download SSH Private Key'
  - script: |
      mkdir -p ~/.ssh
      cp $(sshKey.secureFilePath) ~/.ssh/id_rsa
      chmod 600 ~/.ssh/id_rsa
      echo "StrictHostKeyChecking no" >> ~/.ssh/config
    displayName: 'Configure SSH Key'
  - script: |
      echo "Checking SSH connection"
      ssh -vvv -t web@65.21.20.215 "pwd && ls -al"
    displayName: 'Verify SSH Connection'
  - script: |
      echo "Installing dependencies for Backend"
      cd backend/backend_admintool
      yarn install
    displayName: 'Install dependencies'
  - script: |
      echo "Building Backend"
      cd backend/backend_admintool
      yarn build
    displayName: 'Build Backend'
  - script: |
      echo "Deploying Backend to server using rsync"
      BUILD_ID=$(date +%Y%m%d%H%M%S)
      ssh web@65.21.20.215 "mkdir -p /home/web/backoffice.admintool/releases/backend_$BUILD_ID"
      rsync -avz backend/backend_admintool/dist/ web@65.21.20.215:/home/web/backoffice.admintool/releases/backend_$BUILD_ID
      ssh web@65.21.20.215 "ln -sfn /home/web/backoffice.admintool/releases/backend_$BUILD_ID /home/web/backoffice.admintool/releases/backend_production_temp"
    displayName: 'Deploy Backend'
  - script: |
      echo "Switching symlink to the new release"
      ssh web@65.21.20.215 "mv -Tf /home/web/backoffice.admintool/releases/backend_production_temp /home/web/backoffice.admintool/releases/backend_production"
    displayName: 'Switch Backend Symlink'
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'backend/backend_admintool/dist'
      ArtifactName: 'backend_dist'
      publishLocation: 'Container'
    displayName: 'Publish Backend Artifacts'
