version: '3.8'

services:
  backend_admintool:
    image: node:20
    container_name: backend_admintool
    working_dir: /usr/src/app
    volumes:
      - ./dist:/usr/src/app
    command: "sh -c 'yarn install && yarn start'"
    environment:
      - NODE_ENV=production
    labels:
      - "traefik.http.routers.backend_admintool.rule=Host(`backend-admintool.backoffice.mhub.se`)"
      - "traefik.http.routers.backend_admintool.entrypoints=websecure"
      - "traefik.http.routers.backend_admintool.tls.certresolver=mycompany"
      - "traefik.http.services.backend_admintool.loadbalancer.server.port=3000"
    expose:
      - "3000"
    networks:
      - mycompanynetwork

networks:
  mycompanynetwork:
    external: true
