version: '3.8'

services:
  backend_admintool:
    image: node:20
    container_name: backend_admintool
    working_dir: /usr/src/app
    volumes:
      - ./dist:/usr/src/app/dist
      - ./src:/usr/src/app/src
      - ./node_modules:/usr/src/app/node_modules
      - ./nest-cli.json:/usr/src/app/nest-cli.json
      - ./package.json:/usr/src/app/package.json
      - ./yarn.lock:/usr/src/app/yarn.lock
      - ./tsconfig.json:/usr/src/app/tsconfig.json
    command: "sh -c 'yarn run start:prod'"
    environment:
      - NODE_ENV=production
    labels:
      - "traefik.http.routers.backend_admintool.rule=Host(`backend-admintool.backoffice.mhub.se`)"
      - "traefik.http.routers.backend_admintool.entrypoints=websecure"
      - "traefik.http.routers.backend_admintool.tls.certresolver=mycompany"
      - "traefik.http.services.backend_admintool.loadbalancer.server.port=3000"
      
      - "traefik.http.routers.backend_admintool.middlewares=backend_admintool_cors,backend_admintool_whitelist"

      - "traefik.http.middlewares.backend_admintool_whitelist.ipwhitelist.sourcerange=89.78.20.208/32,89.78.20.208/32"

      - "traefik.http.middlewares.backend_admintool_cors.headers.accesscontrolallowmethods=GET,POST,PUT,DELETE,OPTIONS"
      - "traefik.http.middlewares.backend_admintool_cors.headers.accesscontrolalloworiginlist=https://frontend-admintool.backoffice.mhub.se"
      - "traefik.http.middlewares.backend_admintool_cors.headers.accesscontrolallowcredentials=true"
      - "traefik.http.middlewares.backend_admintool_cors.headers.accesscontrolallowheaders=*"
      - "traefik.http.routers.backend_admintool.middlewares=backend_admintool_cors"
    expose:
      - "3000"
    networks:
      - mycompanynetwork

networks:
  mycompanynetwork:
    external: true
