version: '3.8'

services:
  frontend_admintool:
    image: nginx:latest
    container_name: frontend_admintool
    labels:
      - "traefik.http.routers.frontend_admintool.rule=Host(`frontend-admintool.backoffice.mhub.se`)"
      - "traefik.http.routers.frontend_admintool.entrypoints=websecure"
      - "traefik.http.routers.frontend_admintool.tls.certresolver=mycompany"
      - "traefik.http.services.frontend_admintool.loadbalancer.server.port=80"
      - "traefik.http.routers.frontend_admintool.middlewares=frontend_admintool_whitelist"
      - "traefik.http.middlewares.frontend_admintool_whitelist.ipwhitelist.sourcerange=89.78.20.208/32,89.78.20.208/32"
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx_config/nginx.conf:/etc/nginx/conf.d/default.conf:ro

    expose:
      - "80"
    networks:
      - mycompanynetwork

networks:
  mycompanynetwork:
    external: true
